version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.1.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - node/test:
          app-dir: ~/project/backend
      - eb/deploy:
          app-dir: ~/project/backend
          context: aws-creds
          application-name: AT-EB-Deploy
          environment-name: Atebdeploy-env
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
          requires:
            - node/test
